name: Persistent 12-Hour SSH VM

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  start-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore Previous Files (from branch or artifacts)
      run: |
        mkdir -p restore
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone --depth 1 --single-branch --branch backup https://github.com/${{ github.repository }} restore || echo "No backup branch"
        cp -r restore/data/* ~/ || echo "Nothing to restore"

    - name: Setup Tmate SSH
      uses: mxschmitt/action-tmate@v3

    - name: Save Home Directory to Repo
      if: always()
      run: |
        mkdir -p save/data
        cp -r ~/ save/data/
        cd save
        git init
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git checkout -b backup
        git add .
        git commit -m "Auto backup $(date)"
        git push -f origin backup
